apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_PORT: <YOUR_APP_PORT>
  AWS_REGION: <YOUR_AWS_REGION>
  AWS_SQS_QUEUE_URL: <YOUR_AWS_SQS_QUEUE_URL>
  AWS_SQS_QUEUE_ARN: <YOUR_AWS_SQS_QUEUE_ARN>
